version: '3'

volumes:
  mysql_data:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mrelife_local_django
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start
    environment:
      - MYSQL_DATABASES=mrelife
      - MYSQL_ROOT_PASSWORD=46KTc24KDR9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=46KTc24KDR
      - MYSQL_PASSWORD=9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_LOYALTY_DATABASE=mrelife

  mysql:
    image: mysql:5.7
    depends_on:
      - redis
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASES=mrelife
      - MYSQL_ROOT_PASSWORD=46KTc24KDR9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=46KTc24KDR
      - MYSQL_PASSWORD=9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_LOYALTY_DATABASE=mrelife

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: mrelife_local_celeryworker
    depends_on:
      - redis
      - mysql

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: mrelife_local_celerybeat
    depends_on:
      - redis
      - mysql

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: mrelife_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
