version: '3'

volumes:
  mysql_data:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mrelife_local_django
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - "8000:8000"
    command: /start

  mysql:
    image: mysql:5.7
    depends_on:
      - redis
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.envs/.production/.mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: mrelife_local_celeryworker
    depends_on:
      - redis
      - mysql

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: mrelife_local_celerybeat
    depends_on:
      - redis
      - mysql

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: mrelife_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
