version: '3'

volumes:
  mysql_data:
  static-volume:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mrelife_production_django
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
    command: /start
    environment:
      - MYSQL_DATABASES=mrelife
      - MYSQL_ROOT_PASSWORD=46KTc24KDR9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=46KTc24KDR
      - MYSQL_PASSWORD=9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_LOYALTY_DATABASE=mrelife

  mysql:
    image: mysql:5.7
    depends_on:
      - redis
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASES=mrelife
      - MYSQL_ROOT_PASSWORD=46KTc24KDR9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=46KTc24KDR
      - MYSQL_PASSWORD=9h2rS8Z5ntuLXDSkYdcR
      - MYSQL_LOYALTY_DATABASE=mrelife

  nginx:
    build: ./compose/production/nginx
    volumes:
      - static-volume:/app/static
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: mrelife_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: mrelife_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: mrelife_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
