# Generated by Django 2.0.8 on 2018-11-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('exhibitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelhouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodelhouse',
            name='modelhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhouses.ModelHouse'),
        ),
        migrations.AddField(
            model_name='eventexhibition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventexhibition',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitions.Exhibition'),
        ),
        migrations.AddField(
            model_name='eventcontactreply',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcontactreply',
            name='event_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_tag', to='events.EventContact'),
        ),
        migrations.AddField(
            model_name='eventcontact',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcontact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
