# Generated by Django 2.0.8 on 2018-11-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodelhouse',
            name='name',
        ),
        migrations.AlterField(
            model_name='eventmodelhouse',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_houses', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventmodelhouse',
            name='modelhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='modelhouses.ModelHouse'),
        ),
    ]
