# Generated by Django 2.0.8 on 2018-11-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181115_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contact', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventcontactreply',
            name='event_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contact_reply', to='events.EventContact'),
        ),
        migrations.AlterField(
            model_name='eventexhibition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_exhibition', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventexhibition',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_event', to='exhibitions.Exhibition'),
        ),
    ]
