# Generated by Django 2.0.8 on 2018-11-08 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='', upload_to='Images/outletstore/')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('address', models.CharField(max_length=800)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=8)),
                ('area_of_premises', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                (
                    'category',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.Category')),
            ],
            options={
                'db_table': 'outlet_store',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('outlet_store',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlet_store_comment',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('os_comment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStoreComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlet_store_comment_reply',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('outlet_store',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'outlet_store_media',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('outlet_store',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'outlet_store_tag',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='outletstoretag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.Tag'),
        ),
    ]
