# Generated by Django 2.0.8 on 2018-11-14 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img_thumbnail', models.CharField(max_length=800, null=True)),
                ('img_large', models.ImageField(blank=True, null=True, upload_to='')),
                ('latitude', models.TextField(null=True)),
                ('longitude', models.TextField(null=True)),
                ('address', models.CharField(max_length=800)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=8, null=True)),
                ('home_page', models.CharField(max_length=255, null=True)),
                ('traffic', models.CharField(max_length=255, null=True)),
                ('time_serving', models.CharField(max_length=255, null=True)),
                ('regular_holiday', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.District')),
            ],
            options={
                'db_table': 'outlet_store',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_contact', to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'outlet_store_contact',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreContactReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('outlet_store_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStoreContact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlet_store_contact_reply',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('url', models.CharField(max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('outlet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_media', to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'outlet_store_media',
                'ordering': ['created'],
            },
        ),
    ]
