# Generated by Django 2.0.8 on 2018-11-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstorecontactreply',
            name='outlet_store_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_contact_relpy', to='outletstores.OutletStoreContact'),
        ),
    ]
