# Generated by Django 2.0.8 on 2018-11-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0002_auto_20181115_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstore',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_dict', to='locations.District'),
            preserve_default=False,
        ),
    ]
