# Generated by Django 2.0.8 on 2018-11-13 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outletstores', '0003_auto_20181112_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStoreContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlet_store_contact',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OutletStoreContactReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('outlet_store_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStoreContact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlet_store_contact_reply',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='area_of_premises',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='category',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='outletstore',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='districts.District'),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='home_page',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='img_large',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='img_thumbnail',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='regular_holiday',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='time_serving',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='traffic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outletstore',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outletstore',
            name='longitude',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outletstore',
            name='zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='outletstoremedia',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outletstoremedia',
            name='outlet_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_media', to='outletstores.OutletStore'),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='outlet_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_contact', to='outletstores.OutletStore'),
        ),
    ]
