# Generated by Django 2.0.8 on 2018-11-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0004_auto_20181113_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstorecomment',
            name='outlet_store',
        ),
        migrations.RemoveField(
            model_name='outletstorecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outletstorecommentreply',
            name='os_comment',
        ),
        migrations.RemoveField(
            model_name='outletstorecommentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outletstoretag',
            name='outlet_store',
        ),
        migrations.RemoveField(
            model_name='outletstoretag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='OutletStoreComment',
        ),
        migrations.DeleteModel(
            name='OutletStoreCommentReply',
        ),
        migrations.DeleteModel(
            name='OutletStoreTag',
        ),
    ]
