# Generated by Django 2.0.8 on 2018-12-17 04:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outletstores', '0006_auto_20181205_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStoreReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user_outletstore_review', to=settings.AUTH_USER_MODEL)),
                ('outlet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_review', to='outletstores.OutletStore')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_user_outletstore_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlet_store_review',
                'ordering': ['created'],
            },
        ),
    ]
