# Generated by Django 2.0.8 on 2018-12-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0008_auto_20181224_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstoremedia',
            name='outlet_store',
        ),
        migrations.DeleteModel(
            name='OutletStoreMedia',
        ),
    ]
