# Generated by Django 2.0.8 on 2019-01-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0009_auto_20181224_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstorecontactreply',
            name='outlet_store_contact',
        ),
        migrations.RemoveField(
            model_name='outletstorecontactreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outletstorecontact',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='outletstorecontact',
            name='create_user',
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='OutletStoreContactReply',
        ),
    ]
