# Generated by Django 2.0.8 on 2019-01-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0010_auto_20190102_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstorecontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
