# Generated by Django 2.0.8 on 2019-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0011_outletstorecontact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstorecontact',
            name='acreage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='address',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='budger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='construction_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='construction_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='construction_position_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='construction_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='current_situation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='household_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='household_size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='name_kana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='tel',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
