# Generated by Django 2.0.8 on 2019-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0013_auto_20190102_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstorecontact',
            name='acreage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='budger',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_position_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='current_situation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='household_income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='name_kana',
            field=models.CharField(max_length=255),
        ),
    ]
