# Generated by Django 2.0.8 on 2019-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0014_auto_20190102_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstorecontact',
            name='acreage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='budger',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='current_situation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='household_income',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='household_size',
            field=models.CharField(max_length=255),
        ),
    ]
