# Generated by Django 2.0.8 on 2019-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0015_auto_20190104_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstorecontact',
            name='acreage',
            field=models.CharField(choices=[(1, '20坪以下'), (2, '20坪台'), (3, '30坪台'), (4, '40坪台'), (5, '50坪台'), (6, '60坪台'), (7, '70坪台'), (8, '80坪台'), (9, '90坪以上')], default='20坪以下', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='budger',
            field=models.CharField(choices=[(1, '1500万未満'), (2, '1500万〜3000万'), (3, '3000万〜6000万'), (4, '6000万以上')], default='1500万未満', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_duration',
            field=models.CharField(choices=[(1, '3ヵ月以内'), (2, '6ヵ月以内'), (3, '1年以内'), (4, '1～2年以内'), (5, '2～3年以内'), (6, '未定')], default='3ヵ月以内', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_position_type',
            field=models.CharField(choices=[(1, '現住所と同じ'), (2, '未定'), (3, '予定地を入力')], default='現住所と同じ', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='construction_type',
            field=models.CharField(choices=[(1, '新規'), (2, '建て替え'), (3, 'リフォーム'), (4, 'リノベーション')], default='新規', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='current_situation',
            field=models.CharField(choices=[(1, '住宅・リフォーム・リノベの検討を始めた'), (2, '住宅・リフォーム・リノベ情報収集をしている（個別の会社とはまだ接触していない）'), (3, '工務店・ハウスメーカーと契約した'), (4, '工事に着手している'), (5, 'すでに完成している'), (6, 'その他')], default='住宅・リフォーム・リノベの検討を始めた', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='household_income',
            field=models.CharField(choices=[(1, '350万未満以下'), (2, '350万〜500万未満'), (3, '500万〜800万未満'), (4, '800万〜1000万未満'), (5, '1000万〜1500万未満'), (6, '1500万〜2000万未満'), (7, '2000万以上')], default='350万未満以下', max_length=255),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='household_size',
            field=models.CharField(choices=[(1, '1名〜2名'), (2, '3名〜4名'), (3, '5名〜6名'), (4, '7名以上')], default='1名〜2名', max_length=255),
        ),
    ]
