# Generated by Django 2.0.8 on 2019-01-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20190105_0757'),
        ('outletstores', '0016_auto_20190104_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStoreBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'outlet_store_business',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='district',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='regular_holiday',
        ),
        migrations.RemoveField(
            model_name='outletstore',
            name='traffic',
        ),
        migrations.AddField(
            model_name='outletstore',
            name='charter_capital',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_dict', to='locations.City'),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='construction_area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='construction_result',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='employee_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='establish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='max_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='min_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='permit_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outletstorebusiness',
            name='outlet_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_store_business', to='outletstores.OutletStore'),
        ),
    ]
