# Generated by Django 2.0.8 on 2019-01-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0017_auto_20190105_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstorebusiness',
            name='business',
            field=models.IntegerField(default=1),
        ),
    ]
