# Generated by Django 2.0.8 on 2019-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0018_outletstorebusiness_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstore',
            name='slogan_content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outletstore',
            name='slogan_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
