# Generated by Django 2.0.8 on 2019-01-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0019_auto_20190105_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outletstorecontact',
            old_name='budger',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='outletstorecontact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='outletstorebusiness',
            name='outlet_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='outletstores.OutletStore'),
        ),
        migrations.AlterField(
            model_name='outletstorecontact',
            name='outlet_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='outletstores.OutletStore'),
        ),
        migrations.AlterField(
            model_name='outletstorereview',
            name='outlet_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='outletstores.OutletStore'),
        ),
    ]
