# Generated by Django 2.0.8 on 2019-01-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0020_auto_20190109_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstorecontact',
            name='status',
            field=models.IntegerField(choices=[(1, 'new contact'), (2, 'responded')], default=1),
        ),
    ]
