# Generated by Django 2.0.8 on 2019-01-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletstores', '0022_auto_20190110_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstore',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
