# Generated by Django 2.0.8 on 2018-11-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('outletstores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='', upload_to='Images/ModernHouses/')),
                ('area_of_premises', models.CharField(max_length=50)),
                ('num_attend', models.IntegerField()),
                ('price', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                (
                    'category',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.Category')),
                ('create_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modern_house',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModernHouseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('modern_house',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modernhouses.ModernHouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modern_house_comment',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModernHouseCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('modern_house_comment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modernhouses.ModernHouseComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modern_house_comment_reply',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModernHouseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('modern_house',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modernhouses.ModernHouse')),
            ],
            options={
                'db_table': 'modern_house_media',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModernHouseOutletStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('modern_house',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modernhouses.ModernHouse')),
                ('outlet_store',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'modern_house_outlet_store',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModernHouseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('modern_house',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modernhouses.ModernHouse')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.Tag')),
            ],
            options={
                'db_table': 'modern_house_tag',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModernHouseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('moder_nhouse',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modernhouses.ModernHouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modern_house_user',
                'ordering': ['created'],
            },
        ),
    ]
