version: '3'

volumes:
  mysql_data:
  static-volume:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mrelife_production_django
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start
    expose:
      - "5000"
    volumes:
      - static-volume:/app/static

  mysql:
    image: mysql:5.7
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    build: ./compose/production/nginx
    volumes:
      - static-volume:/app/static
    depends_on:
      - django
    ports:
      - "8000:8000"
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: mrelife_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: mrelife_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: mrelife_production_flower
    ports:
      - "5555:5555"
    command: /start-flower

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 9191:80
    environment:
      MYSQL_USERNAME: 46KTc24KDR
      MYSQL_ROOT_PASSWORD: 9h2rS8Z5ntuLXDSkYdcR
      PMA_HOST: mysql