version: '3'

volumes:
  mysql_data:
  static-volume:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mrelife_production_django
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start
    expose:
      - "5000"
    volumes:
      - static-volume:/app/static

  mysql:
    image: mysql:5.7
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  nginx:
    build: ./compose/production/nginx
    volumes:
      - static-volume:/app/static
    depends_on:
      - django
    ports:
      - "8000:8000"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: mrelife_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: mrelife_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: mrelife_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
