# Generated by Django 2.0.8 on 2018-11-14 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outletstores', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('contruction_method', models.TextField()),
                ('property_feature', models.TextField(null=True)),
                ('manufacturer_name', models.CharField(max_length=255, null=True)),
                ('structure', models.CharField(max_length=255, null=True)),
                ('floor_map', models.CharField(max_length=255, null=True)),
                ('img_thumbnail', models.CharField(max_length=800, null=True)),
                ('img_large', models.ImageField(blank=True, null=True, upload_to='')),
                ('land_area', models.CharField(max_length=255, null=True)),
                ('construction_area', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'model_house',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModelHouseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modern_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_house_contact', to='modelhouses.ModelHouse')),
            ],
            options={
                'db_table': 'model_house_contact',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModelHouseContactReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('modern_house_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhouses.ModelHouseContact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_house_contact_reply',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModelHouseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.BooleanField()),
                ('img_type', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('url', models.CharField(max_length=800)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('modern_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhouses.ModelHouse')),
            ],
            options={
                'db_table': 'model_house_media',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModelHouseOutletStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('model_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhouses.ModelHouse')),
                ('outlet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'model_house_outlet_store',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModelHouseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('model_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhouses.ModelHouse')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag')),
            ],
            options={
                'db_table': 'model_house_tag',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ModelHouseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('model_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelhouses.ModelHouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_house_user',
                'ordering': ['created'],
            },
        ),
    ]
