# Generated by Django 2.0.8 on 2018-11-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelhouses', '0002_auto_20181115_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelhouse',
            name='outlet_store',
        ),
        migrations.AlterField(
            model_name='modelhouse',
            name='img_thumbnail',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
