# Generated by Django 2.0.8 on 2018-11-16 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelhouses', '0003_auto_20181115_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelhousemedia',
            name='img_type',
        ),
        migrations.RemoveField(
            model_name='modelhousemedia',
            name='type_media',
        ),
        migrations.AlterField(
            model_name='modelhouse',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_model_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelhouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelhouse',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
