# Generated by Django 2.0.8 on 2018-11-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelhouses', '0004_auto_20181116_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelhouse',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
