# Generated by Django 2.0.8 on 2018-11-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelhouses', '0005_auto_20181123_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhouse',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelhouse',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
