# Generated by Django 2.0.8 on 2018-11-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelhouses', '0006_auto_20181123_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelhouse',
            options={},
        ),
        migrations.RemoveField(
            model_name='modelhouse',
            name='created',
        ),
        migrations.RemoveField(
            model_name='modelhouse',
            name='updated',
        ),
    ]
