# Generated by Django 2.0.8 on 2018-11-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelhouses', '0007_auto_20181123_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelhouse',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='modelhouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modelhouse',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelhousetag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelhousetag',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelhouseuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelhouseuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
