# Generated by Django 2.0.8 on 2018-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181105_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_thumb',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
