# Generated by Django 2.0.8 on 2018-12-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181116_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lanway_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
