# Generated by Django 2.0.8 on 2018-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('participation_fee', models.FloatField(default=0)),
                ('per_booking_fee', models.FloatField(default=0)),
                ('per_model_house_fee', models.FloatField(default=0)),
                ('per_example_house_fee', models.FloatField(default=0)),
                ('per_article_fee', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'fee',
                'ordering': ['created'],
            },
        ),
    ]
