# Generated by Django 2.0.8 on 2018-12-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outletstores', '0006_auto_20181205_0336'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('has_participation_fee', models.FloatField(default=0)),
                ('booking_number', models.FloatField(default=0)),
                ('model_house_number', models.FloatField(default=0)),
                ('example_house_number', models.FloatField(default=0)),
                ('article_number', models.FloatField(default=0)),
                ('total_fee', models.FloatField(default=0)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='fees.Fee')),
                ('outlet_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='outletstores.OutletStore')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['created'],
            },
        ),
    ]
