#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


export CELERY_BROKER_URL="${REDIS_URL}"

export MYSQL_USER="46KTc24KDR"

export DATABASE_URL="mysql://46KTc24KDR:9h2rS8Z5ntuLXDSkYdcR@mysql:3306/mrelife"

mysql_ready() {
python << END
import sys

import pymysql

try:
    pass
except Exception:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"
