# Generated by Django 2.0.8 on 2019-01-10 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_search', models.IntegerField()),
                ('key_search', models.CharField(max_length=255, unique=True)),
                ('num_result', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchhistorys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['created'],
            },
        ),
    ]
