# Generated by Django 2.0.8 on 2019-01-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_auto_20190110_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='type_search',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='key_search',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='num_result',
            field=models.IntegerField(default=1),
        ),
    ]
