# Generated by Django 2.0.8 on 2018-11-20 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_contact', to='exhibitions.Exhibition')),
            ],
            options={
                'db_table': 'exhibition_contact',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionContactReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exhibition_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_contact_reply', to='exhibitions.Exhibition')),
            ],
            options={
                'db_table': 'exhibition_contact_reply',
                'ordering': ['created'],
            },
        ),
    ]
