# Generated by Django 2.0.8 on 2018-12-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_exhibitiontag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='img_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
