# Generated by Django 2.0.8 on 2019-01-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20181206_0832'),
        ('exhibitions', '0006_auto_20181228_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='district',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
    ]
