# Generated by Django 2.0.8 on 2018-12-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20181205_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
    ]
