# Generated by Django 2.0.8 on 2018-12-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20181206_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
    ]
