# Generated by Django 2.0.8 on 2019-01-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20181206_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'Region',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
    ]
