# Generated by Django 2.0.8 on 2019-01-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20190105_0757'),
        ('outletstores', '0017_auto_20190105_0757'),
        ('exhibitions', '0007_auto_20190105_0757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='locations.Region'),
        ),
    ]
