# Generated by Django 2.0.8 on 2018-11-28 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('outletstores', '0003_auto_20181127_0303'),
        ('attributes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img_thumbnail', models.CharField(blank=True, max_length=800, null=True)),
                ('img_large', models.ImageField(blank=True, null=True, upload_to='')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('status_flag', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.Contruction')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_example_houses', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.Floor')),
                ('household_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.HouseHoldSize')),
                ('househole_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.HouseHoldIncome')),
                ('price_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.PriceRange')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='outletstores.OutletStore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExampleHouseCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.Commitment')),
                ('example_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='examplehouses.ExampleHouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExampleHouseStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('example_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='examplehouses.ExampleHouse')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='attributes.Style')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExampleHouseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('example_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_tags', to='examplehouses.ExampleHouse')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_houses', to='tags.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
