# Generated by Django 2.0.8 on 2018-12-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examplehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplehouse',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creating_example_houses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
