# Generated by Django 2.0.8 on 2018-12-03 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examplehouses', '0002_auto_20181203_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplehouse',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_example_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
