# Generated by Django 2.0.8 on 2018-12-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examplehouses', '0004_examplehousereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplehouse',
            old_name='househole_income',
            new_name='household_income',
        ),
    ]
