# Generated by Django 2.0.8 on 2018-12-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examplehouses', '0005_auto_20181219_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplehouse',
            options={'ordering': ['-created']},
        ),
    ]
