# Generated by Django 2.0.8 on 2018-12-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examplehouses', '0006_auto_20181221_0334'),
        ('examplehouses', '0006_auto_20181221_0601'),
    ]

    operations = [
    ]
